export const LOADING = "SHOWES/LOADING";
export const FAILURE = "SHOWES/FAILURE";

export const GET_SHOWS_SUCCESS = "SHOWES/GET_SHOWES_SUCCESS";
export const COLLAPSE = "SHOWES/COLLAPSE";

export const STAR_CHANGER = "SHOWES/STAR_CHANGER";
export const DELETE_SHOW_SUCCESS = "SHOWES/DELETE_SHOW_SUCCESS";
export const GET_SHOW_SUCCESS = "SHOWES/GET_SHOW_SUCCESS";
export const DELETE_SHOWS_SUCCESS = "SHOWS/DELETE_SHOWs_SUCCESS";
